import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Demo1',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ja' suppressHydrationWarning={true}>
			<body>{children}</body>
		</html>
	);
}
